/**
 * Phase E — Potential Trades
 *
 * Creates a frozen Potential Trade snapshot when
 * the Decision Engine returns CONFIRM.
 *
 * This module does NOT:
 * - execute trades
 * - create Paper Trades
 * - call a broker
 * - modify existing snapshots
 */


/**
 * Returns the Potential_Trades sheet.
 */
function getPotentialTradesSheet() {
  const spreadsheet =
    SpreadsheetApp.getActiveSpreadsheet();

  const sheet =
    spreadsheet.getSheetByName('Potential_Trades');

  if (!sheet) {
    throw new Error(
      'Potential_Trades sheet was not found.'
    );
  }

  return sheet;
}


/**
 * Generates a unique Potential Trade ID.
 */
function generatePotentialTradeId() {
  return (
    'PT-' +
    Utilities.formatDate(
      new Date(),
      Session.getScriptTimeZone(),
      'yyyyMMdd-HHmmss'
    ) +
    '-' +
    Math.floor(Math.random() * 1000)
  );
}


/**
 * Creates a Potential Trade snapshot.
 *
 * Only CONFIRM decisions are recorded.
 */
function createPotentialTrade(
  symbol,
  settings,
  higherTF,
  lowerTF,
  volumeDivergence,
  targetAnalysis,
  decision
) {
  /*
   * -----------------------------------------------
   * Validate inputs
   * -----------------------------------------------
   */

  if (!symbol) {
    return {
      status: 'DATA ERROR',
      message: 'Stock symbol is required.'
    };
  }

  if (!decision) {
    return {
      status: 'DATA ERROR',
      message: 'Decision result is required.'
    };
  }

  if (decision.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Decision Engine did not return OK status.'
    };
  }

  /*
   * Only CONFIRM creates a Potential Trade.
   */
  if (
    decision.finalDecision !== 'CONFIRM'
  ) {
    return {
      status: 'NO TRADE',
      message:
        'Potential Trade not created because final decision is ' +
        decision.finalDecision + '.',
      finalDecision:
        decision.finalDecision
    };
  }

  /*
   * -----------------------------------------------
   * Required data validation
   * -----------------------------------------------
   */

  if (!higherTF || higherTF.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Higher timeframe analysis is unavailable.'
    };
  }

  if (!lowerTF || lowerTF.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Lower timeframe analysis is unavailable.'
    };
  }

  if (
    !targetAnalysis ||
    targetAnalysis.status !== 'OK'
  ) {
    return {
      status: 'DATA ERROR',
      message:
        'Target analysis is unavailable.'
    };
  }

  /*
   * -----------------------------------------------
   * Create frozen snapshot
   * -----------------------------------------------
   */

  const now = new Date();

  const tradeId =
    generatePotentialTradeId();

  const signalDate =
    Utilities.formatDate(
      now,
      Session.getScriptTimeZone(),
      'yyyy-MM-dd'
    );

  const signalTime =
    Utilities.formatDate(
      now,
      Session.getScriptTimeZone(),
      'HH:mm:ss'
    );

  /*
   * Entry reference
   */
  const entryReference =
    Number(
      lowerTF.currentPrice
    );

  /*
   * Target 1
   *
   * Current V1 target engine provides the nearest
   * resistance target.
   */
  const t1 =
    Number(
      targetAnalysis.targetPrice
    );

  /*
   * T1 percentage.
   */
  const t1Percent =
    Number(
      targetAnalysis.potentialReturn
    ) / 100;

  /*
   * T2 is not yet generated by the current
   * Target Engine.
   *
   * Keep blank rather than inventing a value.
   */
  const t2 = '';

  const t2Percent = '';

  /*
   * -----------------------------------------------
   * Settings
   * -----------------------------------------------
   */

  const higherTimeframe =
    String(
      settings['Higher Timeframe'] || ''
    ).trim();

  const lowerTimeframe =
    String(
      settings['Lower Timeframe'] || ''
    ).trim();

  const simulationMode =
    String(
      settings['Simulation Mode'] || ''
    ).trim();

  const simulationAmount =
    Number(
      settings['Simulation Amount']
    );

  const simulationQuantity =
    Number(
      settings['Fixed Quantity']
    );

  /*
   * -----------------------------------------------
   * Snapshot row
   * -----------------------------------------------
   */

  const row = [
    tradeId,
    signalDate,
    signalTime,
    symbol,
    symbol,
    higherTimeframe,
    lowerTimeframe,
    entryReference,
    t1,
    t2,
    t1Percent,
    t2Percent,
    higherTF.context || '',
    lowerTF.context || '',
    volumeDivergence.divergence || 'NONE',
    targetAnalysis.potentialReturnPercent,
    decision.conditionsSatisfied,
    decision.totalConditions,
    decision.finalDecision,
    decision.primaryReason,
    decision.secondaryReason,
    'NO',
    simulationMode,
    simulationAmount,
    simulationQuantity,
    'FROZEN'
  ];

  /*
   * -----------------------------------------------
   * Write snapshot
   * -----------------------------------------------
   */

  const sheet =
    getPotentialTradesSheet();

  sheet.appendRow(row);

  return {
    status: 'OK',
    message:
      'Potential Trade created successfully.',

    tradeId:
      tradeId,

    finalDecision:
      decision.finalDecision,

    entryReference:
      entryReference,

    targetPrice:
      t1,

    potentialReturn:
      t1Percent,

    snapshotStatus:
      'FROZEN'
  };
}

/**
 * Phase E — Potential Trades
 *
 * Creates a frozen Potential Trade snapshot when
 * the Decision Engine returns CONFIRM.
 *
 * This module does NOT:
 * - execute trades
 * - create Paper Trades
 * - call a broker
 * - modify existing snapshots
 */


/**
 * Tests Potential Trade creation using
 * the current RELIANCE.NS analysis.
 */
function runPotentialTradeTest() {
  try {
    const settings =
      getSettings();

    const validation =
      validateSettings(settings);

    if (!validation.valid) {
      SpreadsheetApp.getUi().alert(
        'Settings validation failed:\n\n' +
        validation.errors.join('\n')
      );
      return;
    }

    const symbol =
      'INDUSTOWER.NS';

    /*
     * Higher timeframe analysis
     */
    const higherTF =
      analyzeHigherTimeframe(
        symbol,
        settings
      );

    if (higherTF.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Higher TF analysis failed:\n\n' +
        higherTF.message
      );
      return;
    }

    /*
     * Lower timeframe analysis
     */
    const lowerTF =
      analyzeLowerTimeframe(
        symbol,
        settings
      );

    if (lowerTF.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Lower TF analysis failed:\n\n' +
        lowerTF.message
      );
      return;
    }

    /*
     * Lower timeframe market data
     * for volume divergence.
     */
    const candleLookback =
      Number(
        settings['Candle Lookback']
      );

    const volumeLookback =
      Number(
        settings['Volume Lookback']
      );

    const requiredCandles =
      Math.max(
        candleLookback,
        volumeLookback + 1
      );

    const marketData =
      getYahooData(
        symbol,
        settings['Lower Timeframe'],
        requiredCandles
      );

    if (marketData.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Market data failed:\n\n' +
        marketData.message
      );
      return;
    }

    const volumeDivergence =
      analyzeVolumeDivergence(
        marketData.candles,
        Number(
          settings['Volume Lookback']
        )
      );

    if (
      volumeDivergence.status !== 'OK'
    ) {
      SpreadsheetApp.getUi().alert(
        'Volume divergence failed:\n\n' +
        volumeDivergence.message
      );
      return;
    }

    /*
     * Target
     */
    const targetAnalysis =
      calculateTarget(
        lowerTF.currentPrice,
        lowerTF.resistance,
        Number(
          settings['Minimum Target %']
        )
      );

    if (
      targetAnalysis.status !== 'OK'
    ) {
      SpreadsheetApp.getUi().alert(
        'Target calculation failed:\n\n' +
        targetAnalysis.message
      );
      return;
    }

    /*
     * Decision
     */
    const decision =
      evaluateDecision(
        higherTF,
        lowerTF,
        volumeDivergence,
        targetAnalysis
      );

    if (decision.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Decision Engine failed:\n\n' +
        decision.message
      );
      return;
    }

    /*
     * Potential Trade
     */
    const result =
      createPotentialTrade(
        symbol,
        settings,
        higherTF,
        lowerTF,
        volumeDivergence,
        targetAnalysis,
        decision
      );

    SpreadsheetApp.getUi().alert(
      'Potential Trade Test\n\n' +
      'Symbol: ' +
      symbol +
      '\n\n' +
      'Decision: ' +
      decision.finalDecision +
      '\n\n' +
      'Result: ' +
      result.status +
      '\n\n' +
      result.message +
      (
        result.tradeId
          ? '\n\nTrade ID: ' +
          result.tradeId
          : ''
      )
    );

  } catch (error) {
    SpreadsheetApp.getUi().alert(
      'Potential Trade test failed:\n\n' +
      error.message
    );
  }
}

/**
 * Test-only controlled CONFIRM scenario.
 *
 * This function does NOT modify the real market-analysis
 * workflow or Decision Engine.
 *
 * It directly tests createPotentialTrade() using a
 * controlled synthetic CONFIRM fixture.
 */
function runPotentialTradeConfirmTest() {
  try {
    const settings =
      getSettings();

    const validation =
      validateSettings(settings);

    if (!validation.valid) {
      SpreadsheetApp.getUi().alert(
        'Settings validation failed:\n\n' +
        validation.errors.join('\n')
      );
      return;
    }

    /*
     * ------------------------------------------------
     * Controlled test fixture
     * ------------------------------------------------
     */
    const symbol =
      'TEST.CONFIRM';

    const higherTF = {
      status: 'OK',
      context: 'POSITIVE'
    };

    const lowerTF = {
      status: 'OK',
      currentPrice: 2500,
      context: 'POSITIVE'
    };

    const volumeDivergence = {
      status: 'OK',
      divergence: 'NONE'
    };

    const targetAnalysis = {
      status: 'OK',
      targetPrice: 2600,

      // Used by createPotentialTrade()
      // for Entry/T1-related calculations.
      potentialReturn: 4,

      // Used by createPotentialTrade()
      // for Target Room.
      potentialReturnPercent: 4
    };

    const decision = {
      status: 'OK',
      finalDecision: 'CONFIRM',

      conditionsSatisfied: 12,
      totalConditions: 12,

      primaryReason:
        'CONTROLLED TEST — CONFIRM',

      secondaryReason:
        'Synthetic test fixture only.'
    };

    /*
     * ------------------------------------------------
     * Capture row count BEFORE creation.
     * ------------------------------------------------
     */
    const sheet =
      getPotentialTradesSheet();

    const rowsBefore =
      sheet.getLastRow();

    /*
     * ------------------------------------------------
     * Create controlled Potential Trade.
     * ------------------------------------------------
     */
    const result =
      createPotentialTrade(
        symbol,
        settings,
        higherTF,
        lowerTF,
        volumeDivergence,
        targetAnalysis,
        decision
      );

    if (result.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'CONFIRM test FAILED\n\n' +
        result.message
      );
      return;
    }

    /*
     * ------------------------------------------------
     * Verify exactly one row was added.
     * ------------------------------------------------
     */
    const rowsAfter =
      sheet.getLastRow();

    if (rowsAfter !== rowsBefore + 1) {
      SpreadsheetApp.getUi().alert(
        'CONFIRM test FAILED\n\n' +
        'Expected exactly one new Potential Trade row.\n\n' +
        'Rows before: ' +
        rowsBefore +
        '\n' +
        'Rows after: ' +
        rowsAfter
      );
      return;
    }

    const rowNumber =
      rowsAfter;

    /*
     * ------------------------------------------------
     * Read the newly-created snapshot.
     *
     * Potential_Trades currently contains
     * 26 data columns.
     * ------------------------------------------------
     */
    const row =
      sheet
        .getRange(
          rowNumber,
          1,
          1,
          26
        )
        .getValues()[0];

    /*
     * ------------------------------------------------
     * Column mapping (0-based array indexes)
     *
     * 0  Trade ID
     * 1  Signal Date
     * 2  Signal Time
     * 3  Stock
     * 4  Yahoo Symbol
     * 5  Higher TF
     * 6  Lower TF
     * 7  Entry Reference
     * 8  T1
     * 9  T2
     * 10 T1 %
     * 11 T2 %
     * 12 Higher TF Context
     * 13 Lower TF Context
     * 14 Volume Divergence
     * 15 Target Room
     * 16 Conditions Satisfied
     * 17 Total Conditions
     * 18 Final Decision
     * 19 Primary Reason
     * 20 Secondary Reason
     * 21 Simulate?
     * 22 Simulation Mode
     * 23 Simulation Amount
     * 24 Simulation Quantity
     * 25 Snapshot Status
     * ------------------------------------------------
     */

    const checks = [];

    checks.push({
      name: 'Trade ID generated',
      passed:
        String(row[0]).trim() !== ''
    });

    checks.push({
      name: 'Signal date recorded',
      passed:
        String(row[1]).trim() !== ''
    });

    checks.push({
      name: 'Signal time recorded',
      passed:
        String(row[2]).trim() !== ''
    });

    checks.push({
      name: 'Entry reference captured',
      passed:
        Number(row[7]) === 2500
    });

    checks.push({
      name: 'T1 captured',
      passed:
        Number(row[8]) === 2600
    });

    checks.push({
      name: 'T1 percentage captured',
      passed:
        Math.abs(
          Number(row[10]) - 0.04
        ) < 0.000001
    });

    checks.push({
      name: 'Target room captured',
      passed:
        Number(row[15]) === 4
    });

    checks.push({
      name: 'Conditions captured',
      passed:
        Number(row[16]) === 12 &&
        Number(row[17]) === 12
    });

    checks.push({
      name: 'Primary reason captured',
      passed:
        row[19] ===
        'CONTROLLED TEST — CONFIRM'
    });

    checks.push({
      name: 'Secondary reason captured',
      passed:
        row[20] ===
        'Synthetic test fixture only.'
    });

    checks.push({
      name: 'Simulate initially NO',
      passed:
        row[21] === 'NO'
    });

    checks.push({
      name: 'Snapshot status FROZEN',
      passed:
        row[25] === 'FROZEN'
    });

    /*
     * ------------------------------------------------
     * Verify the stored snapshot does not change
     * simply by reading it again.
     * ------------------------------------------------
     */
    const snapshotBefore =
      JSON.stringify(row);

    const rowAgain =
      sheet
        .getRange(
          rowNumber,
          1,
          1,
          26
        )
        .getValues()[0];

    const snapshotAfter =
      JSON.stringify(rowAgain);

    checks.push({
      name: 'Snapshot remains unchanged',
      passed:
        snapshotBefore === snapshotAfter
    });

    /*
     * ------------------------------------------------
     * Report failures.
     * ------------------------------------------------
     */
    const failedChecks =
      checks.filter(
        check => !check.passed
      );

    if (failedChecks.length > 0) {
      SpreadsheetApp.getUi().alert(
        'CONFIRM test FAILED\n\n' +
        failedChecks
          .map(
            check =>
              'FAIL: ' +
              check.name
          )
          .join('\n') +
        '\n\nTrade ID: ' +
        result.tradeId +
        '\n\nRow: ' +
        rowNumber
      );

      return;
    }

    /*
     * ------------------------------------------------
     * All checks passed.
     * ------------------------------------------------
     */
    SpreadsheetApp.getUi().alert(
      'Potential Trade CONFIRM Test\n\n' +
      'Status: PASSED\n\n' +
      'Test Symbol: ' +
      symbol +
      '\n\n' +
      'Decision: CONFIRM' +
      '\n\n' +
      'Trade ID: ' +
      result.tradeId +
      '\n\n' +
      'Entry: ' +
      row[7] +
      '\n\n' +
      'T1: ' +
      row[8] +
      '\n\n' +
      'Target Room: ' +
      row[15] +
      '%' +
      '\n\n' +
      'Conditions: ' +
      row[16] +
      '/' +
      row[17] +
      '\n\n' +
      'Simulate?: ' +
      row[21] +
      '\n\n' +
      'Snapshot: ' +
      row[25]
    );

  } catch (error) {
    SpreadsheetApp.getUi().alert(
      'CONFIRM test FAILED:\n\n' +
      error.message
    );
  }
}

/**
 * Test-only frozen snapshot immutability check.
 *
 * Verifies that an existing FROZEN Potential Trade
 * remains unchanged when later market data is simulated.
 *
 * This test does NOT modify the existing snapshot.
 */
function runPotentialTradeFrozenSnapshotTest() {
  try {
    const tradeId =
      'PT-20260928-110416-693';

    const sheet =
      getPotentialTradesSheet();

    const data =
      sheet.getDataRange().getValues();

    if (data.length < 2) {
      SpreadsheetApp.getUi().alert(
        'FROZEN snapshot test FAILED\n\n' +
        'Potential_Trades contains no data rows.'
      );
      return;
    }

    /*
     * Find the requested Trade ID.
     */
    let targetRowNumber = null;

    for (let i = 1; i < data.length; i++) {
      if (
        String(data[i][0]).trim() === tradeId
      ) {
        targetRowNumber = i + 1;
        break;
      }
    }

    if (!targetRowNumber) {
      SpreadsheetApp.getUi().alert(
        'FROZEN snapshot test FAILED\n\n' +
        'Trade ID not found:\n' +
        tradeId
      );
      return;
    }

    /*
     * Read the original snapshot.
     */
    const originalSnapshot =
      sheet
        .getRange(
          targetRowNumber,
          1,
          1,
          26
        )
        .getValues()[0];

    /*
     * Verify the row is actually FROZEN.
     *
     * Snapshot Status = column 26
     * 0-based array index = 25
     */
    if (
      originalSnapshot[25] !== 'FROZEN'
    ) {
      SpreadsheetApp.getUi().alert(
        'FROZEN snapshot test FAILED\n\n' +
        'Trade ID:\n' +
        tradeId +
        '\n\n' +
        'Expected Snapshot Status: FROZEN\n' +
        'Actual: ' +
        originalSnapshot[25]
      );
      return;
    }

    /*
     * Capture values that must remain immutable.
     */
    const originalValues = {
      tradeId: originalSnapshot[0],
      signalDate: originalSnapshot[1],
      signalTime: originalSnapshot[2],
      symbol: originalSnapshot[3],
      entryReference: originalSnapshot[7],
      t1: originalSnapshot[8],
      targetRoom: originalSnapshot[15],
      conditionsSatisfied: originalSnapshot[16],
      totalConditions: originalSnapshot[17],
      finalDecision: originalSnapshot[18],
      primaryReason: originalSnapshot[19],
      secondaryReason: originalSnapshot[20],
      simulate: originalSnapshot[21],
      snapshotStatus: originalSnapshot[25]
    };

    /*
     * ------------------------------------------------
     * Simulate later market data.
     *
     * This deliberately creates a NEW in-memory
     * market-data object. It is NOT written into
     * the existing Potential_Trades row.
     * ------------------------------------------------
     */
    const laterMarketData = {
      symbol: 'TEST.CONFIRM',
      currentPrice: 2750,
      targetPrice: 2850,
      conditionsSatisfied: 4,
      totalConditions: 12,
      finalDecision: 'NO SETUP',
      primaryReason:
        'SIMULATED LATER MARKET DATA',
      secondaryReason:
        'This must not modify the frozen snapshot.'
    };

    /*
     * Keep the simulated object referenced so
     * the test explicitly exercises a later-data
     * scenario without touching persistence.
     */
    if (!laterMarketData) {
      throw new Error(
        'Later market-data fixture was not created.'
      );
    }

    /*
     * Re-read the existing Potential Trade.
     */
    const afterSnapshot =
      sheet
        .getRange(
          targetRowNumber,
          1,
          1,
          26
        )
        .getValues()[0];

    /*
     * ------------------------------------------------
     * Verify immutable values.
     * ------------------------------------------------
     */
    const checks = [];

    checks.push({
      name: 'Trade ID unchanged',
      passed:
        afterSnapshot[0] ===
        originalValues.tradeId
    });

    checks.push({
      name: 'Signal date unchanged',
      passed:
        normalizeSnapshotDate(
          afterSnapshot[1]
        ) ===
        normalizeSnapshotDate(
          originalValues.signalDate
        )
    });

    checks.push({
      name: 'Signal time unchanged',
      passed:
        normalizeSnapshotDate(
          afterSnapshot[2]
        ) ===
        normalizeSnapshotDate(
          originalValues.signalTime
        )
    });

    checks.push({
      name: 'Symbol unchanged',
      passed:
        afterSnapshot[3] ===
        originalValues.symbol
    });

    checks.push({
      name: 'Entry reference unchanged',
      passed:
        afterSnapshot[7] ===
        originalValues.entryReference
    });

    checks.push({
      name: 'T1 unchanged',
      passed:
        afterSnapshot[8] ===
        originalValues.t1
    });

    checks.push({
      name: 'Target room unchanged',
      passed:
        afterSnapshot[15] ===
        originalValues.targetRoom
    });

    checks.push({
      name: 'Conditions unchanged',
      passed:
        afterSnapshot[16] ===
        originalValues.conditionsSatisfied &&
        afterSnapshot[17] ===
        originalValues.totalConditions
    });

    checks.push({
      name: 'Final decision unchanged',
      passed:
        afterSnapshot[18] ===
        originalValues.finalDecision
    });

    checks.push({
      name: 'Primary reason unchanged',
      passed:
        afterSnapshot[19] ===
        originalValues.primaryReason
    });

    checks.push({
      name: 'Secondary reason unchanged',
      passed:
        afterSnapshot[20] ===
        originalValues.secondaryReason
    });

    checks.push({
      name: 'Simulate remains NO',
      passed:
        afterSnapshot[21] ===
        originalValues.simulate &&
        afterSnapshot[21] === 'NO'
    });

    checks.push({
      name: 'Snapshot remains FROZEN',
      passed:
        afterSnapshot[25] ===
        originalValues.snapshotStatus &&
        afterSnapshot[25] === 'FROZEN'
    });

    /*
     * Complete row comparison.
     */
    checks.push({
      name: 'Complete snapshot unchanged',
      passed:
        JSON.stringify(originalSnapshot) ===
        JSON.stringify(afterSnapshot)
    });

    const failedChecks =
      checks.filter(
        check => !check.passed
      );

    if (failedChecks.length > 0) {
      SpreadsheetApp.getUi().alert(
        'FROZEN snapshot test FAILED\n\n' +
        failedChecks
          .map(
            check =>
              'FAIL: ' +
              check.name
          )
          .join('\n') +
        '\n\nTrade ID: ' +
        tradeId
      );

      return;
    }

    SpreadsheetApp.getUi().alert(
      'FROZEN Snapshot Test\n\n' +
      'Status: PASSED\n\n' +
      'Trade ID: ' +
      tradeId +
      '\n\n' +
      'Original Entry: ' +
      originalValues.entryReference +
      '\n\n' +
      'Original T1: ' +
      originalValues.t1 +
      '\n\n' +
      'Snapshot Status: ' +
      originalValues.snapshotStatus +
      '\n\n' +
      'Later market data did not overwrite ' +
      'the existing snapshot.'
    );

  } catch (error) {
    SpreadsheetApp.getUi().alert(
      'FROZEN snapshot test FAILED:\n\n' +
      error.message
    );
  }
}

/**
 * Normalizes a Potential Trade snapshot
 * date/time value for reliable comparison.
 */
function normalizeSnapshotDate(value) {
  if (value instanceof Date) {
    return value.getTime();
  }

  return String(value).trim();
}