/**
 * Phase E — Potential Trades
 *
 * Creates a frozen Potential Trade snapshot when
 * the Decision Engine returns CONFIRM.
 *
 * This module does NOT:
 * - execute trades
 * - create Paper Trades
 * - call a broker
 * - modify existing snapshots
 */


/**
 * Returns the Potential_Trades sheet.
 */
function getPotentialTradesSheet() {
  const spreadsheet =
    SpreadsheetApp.getActiveSpreadsheet();

  const sheet =
    spreadsheet.getSheetByName('Potential_Trades');

  if (!sheet) {
    throw new Error(
      'Potential_Trades sheet was not found.'
    );
  }

  return sheet;
}


/**
 * Generates a unique Potential Trade ID.
 */
function generatePotentialTradeId() {
  return (
    'PT-' +
    Utilities.formatDate(
      new Date(),
      Session.getScriptTimeZone(),
      'yyyyMMdd-HHmmss'
    ) +
    '-' +
    Math.floor(Math.random() * 1000)
  );
}


/**
 * Creates a Potential Trade snapshot.
 *
 * Only CONFIRM decisions are recorded.
 */
function createPotentialTrade(
  symbol,
  settings,
  higherTF,
  lowerTF,
  volumeDivergence,
  targetAnalysis,
  decision
) {
  /*
   * -----------------------------------------------
   * Validate inputs
   * -----------------------------------------------
   */

  if (!symbol) {
    return {
      status: 'DATA ERROR',
      message: 'Stock symbol is required.'
    };
  }

  if (!decision) {
    return {
      status: 'DATA ERROR',
      message: 'Decision result is required.'
    };
  }

  if (decision.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Decision Engine did not return OK status.'
    };
  }

  /*
   * Only CONFIRM creates a Potential Trade.
   */
  if (
    decision.finalDecision !== 'CONFIRM'
  ) {
    return {
      status: 'NO TRADE',
      message:
        'Potential Trade not created because final decision is ' +
        decision.finalDecision + '.',
      finalDecision:
        decision.finalDecision
    };
  }

  /*
   * -----------------------------------------------
   * Required data validation
   * -----------------------------------------------
   */

  if (!higherTF || higherTF.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Higher timeframe analysis is unavailable.'
    };
  }

  if (!lowerTF || lowerTF.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Lower timeframe analysis is unavailable.'
    };
  }

  if (
    !targetAnalysis ||
    targetAnalysis.status !== 'OK'
  ) {
    return {
      status: 'DATA ERROR',
      message:
        'Target analysis is unavailable.'
    };
  }

  /*
   * -----------------------------------------------
   * Create frozen snapshot
   * -----------------------------------------------
   */

  const now = new Date();

  const tradeId =
    generatePotentialTradeId();

  const signalDate =
    Utilities.formatDate(
      now,
      Session.getScriptTimeZone(),
      'yyyy-MM-dd'
    );

  const signalTime =
    Utilities.formatDate(
      now,
      Session.getScriptTimeZone(),
      'HH:mm:ss'
    );

  /*
   * Entry reference
   */
  const entryReference =
    Number(
      lowerTF.currentPrice
    );

  /*
   * Target 1
   *
   * Current V1 target engine provides the nearest
   * resistance target.
   */
  const t1 =
    Number(
      targetAnalysis.targetPrice
    );

  /*
   * T1 percentage.
   */
  const t1Percent =
    Number(
      targetAnalysis.potentialReturn
    );

  /*
   * T2 is not yet generated by the current
   * Target Engine.
   *
   * Keep blank rather than inventing a value.
   */
  const t2 = '';

  const t2Percent = '';

  /*
   * -----------------------------------------------
   * Settings
   * -----------------------------------------------
   */

  const higherTimeframe =
    String(
      settings['Higher Timeframe'] || ''
    ).trim();

  const lowerTimeframe =
    String(
      settings['Lower Timeframe'] || ''
    ).trim();

  const simulationMode =
    String(
      settings['Simulation Mode'] || ''
    ).trim();

  const simulationAmount =
    Number(
      settings['Simulation Amount']
    );

  const simulationQuantity =
    Number(
      settings['Fixed Quantity']
    );

  /*
   * -----------------------------------------------
   * Snapshot row
   * -----------------------------------------------
   */

  const row = [
    tradeId,
    signalDate,
    signalTime,
    symbol,
    symbol,
    higherTimeframe,
    lowerTimeframe,
    entryReference,
    t1,
    t2,
    t1Percent,
    t2Percent,
    higherTF.context || '',
    lowerTF.context || '',
    volumeDivergence.divergence || 'NONE',
    targetAnalysis.potentialReturnPercent,
    decision.conditionsSatisfied,
    decision.totalConditions,
    decision.finalDecision,
    decision.primaryReason,
    decision.secondaryReason,
    'NO',
    simulationMode,
    simulationAmount,
    simulationQuantity,
    'FROZEN'
  ];

  /*
   * -----------------------------------------------
   * Write snapshot
   * -----------------------------------------------
   */

  const sheet =
    getPotentialTradesSheet();

  sheet.appendRow(row);

  return {
    status: 'OK',
    message:
      'Potential Trade created successfully.',

    tradeId:
      tradeId,

    finalDecision:
      decision.finalDecision,

    entryReference:
      entryReference,

    targetPrice:
      t1,

    potentialReturn:
      t1Percent,

    snapshotStatus:
      'FROZEN'
  };
}

/**
 * Phase E — Potential Trades
 *
 * Creates a frozen Potential Trade snapshot when
 * the Decision Engine returns CONFIRM.
 *
 * This module does NOT:
 * - execute trades
 * - create Paper Trades
 * - call a broker
 * - modify existing snapshots
 */


/**
 * Returns the Potential_Trades sheet.
 */
function getPotentialTradesSheet() {
  const spreadsheet =
    SpreadsheetApp.getActiveSpreadsheet();

  const sheet =
    spreadsheet.getSheetByName('Potential_Trades');

  if (!sheet) {
    throw new Error(
      'Potential_Trades sheet was not found.'
    );
  }

  return sheet;
}


/**
 * Generates a unique Potential Trade ID.
 */
function generatePotentialTradeId() {
  return (
    'PT-' +
    Utilities.formatDate(
      new Date(),
      Session.getScriptTimeZone(),
      'yyyyMMdd-HHmmss'
    ) +
    '-' +
    Math.floor(Math.random() * 1000)
  );
}


/**
 * Creates a Potential Trade snapshot.
 *
 * Only CONFIRM decisions are recorded.
 */
function createPotentialTrade(
  symbol,
  settings,
  higherTF,
  lowerTF,
  volumeDivergence,
  targetAnalysis,
  decision
) {
  /*
   * -----------------------------------------------
   * Validate inputs
   * -----------------------------------------------
   */

  if (!symbol) {
    return {
      status: 'DATA ERROR',
      message: 'Stock symbol is required.'
    };
  }

  if (!decision) {
    return {
      status: 'DATA ERROR',
      message: 'Decision result is required.'
    };
  }

  if (decision.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Decision Engine did not return OK status.'
    };
  }

  /*
   * Only CONFIRM creates a Potential Trade.
   */
  if (
    decision.finalDecision !== 'CONFIRM'
  ) {
    return {
      status: 'NO TRADE',
      message:
        'Potential Trade not created because final decision is ' +
        decision.finalDecision + '.',
      finalDecision:
        decision.finalDecision
    };
  }

  /*
   * -----------------------------------------------
   * Required data validation
   * -----------------------------------------------
   */

  if (!higherTF || higherTF.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Higher timeframe analysis is unavailable.'
    };
  }

  if (!lowerTF || lowerTF.status !== 'OK') {
    return {
      status: 'DATA ERROR',
      message:
        'Lower timeframe analysis is unavailable.'
    };
  }

  if (
    !targetAnalysis ||
    targetAnalysis.status !== 'OK'
  ) {
    return {
      status: 'DATA ERROR',
      message:
        'Target analysis is unavailable.'
    };
  }

  /*
   * -----------------------------------------------
   * Create frozen snapshot
   * -----------------------------------------------
   */

  const now = new Date();

  const tradeId =
    generatePotentialTradeId();

  const signalDate =
    Utilities.formatDate(
      now,
      Session.getScriptTimeZone(),
      'yyyy-MM-dd'
    );

  const signalTime =
    Utilities.formatDate(
      now,
      Session.getScriptTimeZone(),
      'HH:mm:ss'
    );

  /*
   * Entry reference
   */
  const entryReference =
    Number(
      lowerTF.currentPrice
    );

  /*
   * Target 1
   *
   * Current V1 target engine provides the nearest
   * resistance target.
   */
  const t1 =
    Number(
      targetAnalysis.targetPrice
    );

  /*
   * T1 percentage.
   */
  const t1Percent =
    Number(
      targetAnalysis.potentialReturn
    );

  /*
   * T2 is not yet generated by the current
   * Target Engine.
   *
   * Keep blank rather than inventing a value.
   */
  const t2 = '';

  const t2Percent = '';

  /*
   * -----------------------------------------------
   * Settings
   * -----------------------------------------------
   */

  const higherTimeframe =
    String(
      settings['Higher Timeframe'] || ''
    ).trim();

  const lowerTimeframe =
    String(
      settings['Lower Timeframe'] || ''
    ).trim();

  const simulationMode =
    String(
      settings['Simulation Mode'] || ''
    ).trim();

  const simulationAmount =
    Number(
      settings['Simulation Amount']
    );

  const simulationQuantity =
    Number(
      settings['Fixed Quantity']
    );

  /*
   * -----------------------------------------------
   * Snapshot row
   * -----------------------------------------------
   */

  const row = [
    tradeId,
    signalDate,
    signalTime,
    symbol,
    symbol,
    higherTimeframe,
    lowerTimeframe,
    entryReference,
    t1,
    t2,
    t1Percent,
    t2Percent,
    higherTF.context || '',
    lowerTF.context || '',
    volumeDivergence.divergence || 'NONE',
    targetAnalysis.potentialReturnPercent,
    decision.conditionsSatisfied,
    decision.totalConditions,
    decision.finalDecision,
    decision.primaryReason,
    decision.secondaryReason,
    'NO',
    simulationMode,
    simulationAmount,
    simulationQuantity,
    'FROZEN'
  ];

  /*
   * -----------------------------------------------
   * Write snapshot
   * -----------------------------------------------
   */

  const sheet =
    getPotentialTradesSheet();

  sheet.appendRow(row);

  return {
    status: 'OK',
    message:
      'Potential Trade created successfully.',

    tradeId:
      tradeId,

    finalDecision:
      decision.finalDecision,

    entryReference:
      entryReference,

    targetPrice:
      t1,

    potentialReturn:
      t1Percent,

    snapshotStatus:
      'FROZEN'
  };
}

/**
 * Tests Potential Trade creation using
 * the current RELIANCE.NS analysis.
 */
function runPotentialTradeTest() {
  try {
    const settings =
      getSettings();

    const validation =
      validateSettings(settings);

    if (!validation.valid) {
      SpreadsheetApp.getUi().alert(
        'Settings validation failed:\n\n' +
        validation.errors.join('\n')
      );
      return;
    }

    const symbol =
      'RELIANCE.NS';

    /*
     * Higher timeframe analysis
     */
    const higherTF =
      analyzeHigherTimeframe(
        symbol,
        settings
      );

    if (higherTF.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Higher TF analysis failed:\n\n' +
        higherTF.message
      );
      return;
    }

    /*
     * Lower timeframe analysis
     */
    const lowerTF =
      analyzeLowerTimeframe(
        symbol,
        settings
      );

    if (lowerTF.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Lower TF analysis failed:\n\n' +
        lowerTF.message
      );
      return;
    }

    /*
     * Lower timeframe market data
     * for volume divergence.
     */
    const marketData =
      getYahooData(
        symbol,
        settings['Lower Timeframe'],
        Number(
          settings['Candle Lookback']
        )
      );

    if (marketData.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Market data failed:\n\n' +
        marketData.message
      );
      return;
    }

    const volumeDivergence =
      analyzeVolumeDivergence(
        marketData.candles,
        Number(
          settings['Volume Lookback']
        )
      );

    if (
      volumeDivergence.status !== 'OK'
    ) {
      SpreadsheetApp.getUi().alert(
        'Volume divergence failed:\n\n' +
        volumeDivergence.message
      );
      return;
    }

    /*
     * Target
     */
    const targetAnalysis =
      calculateTarget(
        lowerTF.currentPrice,
        lowerTF.resistance,
        Number(
          settings['Minimum Target %']
        )
      );

    if (
      targetAnalysis.status !== 'OK'
    ) {
      SpreadsheetApp.getUi().alert(
        'Target calculation failed:\n\n' +
        targetAnalysis.message
      );
      return;
    }

    /*
     * Decision
     */
    const decision =
      evaluateDecision(
        higherTF,
        lowerTF,
        volumeDivergence,
        targetAnalysis
      );

    if (decision.status !== 'OK') {
      SpreadsheetApp.getUi().alert(
        'Decision Engine failed:\n\n' +
        decision.message
      );
      return;
    }

    /*
     * Potential Trade
     */
    const result =
      createPotentialTrade(
        symbol,
        settings,
        higherTF,
        lowerTF,
        volumeDivergence,
        targetAnalysis,
        decision
      );

    SpreadsheetApp.getUi().alert(
      'Potential Trade Test\n\n' +
      'Symbol: ' +
      symbol +
      '\n\n' +
      'Decision: ' +
      decision.finalDecision +
      '\n\n' +
      'Result: ' +
      result.status +
      '\n\n' +
      result.message +
      (
        result.tradeId
          ? '\n\nTrade ID: ' +
            result.tradeId
          : ''
      )
    );

  } catch (error) {
    SpreadsheetApp.getUi().alert(
      'Potential Trade test failed:\n\n' +
      error.message
    );
  }
}
